=== Sage-Bionetworks/nlp-sandbox-schemas/json-schema/schemas/tool.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://nlp-sandbox.org/schemas/tool.json",
    "title": "Tool",
    "description": "A NLP Tool",
    "type": "object",
    "properties": {
        "name": {
          "description": "The Tool name",
          "type": "string",
          "minLength": 3,
          "maxLength": 60,
          "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
        },
        "version": {
            "description": "The version of the Tool (SemVer string)",
            "type": "string",
            "minLength": 1,
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        },
        "license": {
            "description": "The license of this Tool (spdx.org/licenses Identifier)",
            "type": "string"
        },
        "repository": {
            "description": "The place where the code lives",
            "type": "string"
        },
        "description": {
            "description": "A short, one-sentence summary of the Tool",
            "type": "string",
            "maxLength": 100
        },
        "author": {
            "description": "The author of the Tool",
            "type": "string"
        },
        "authorEmail": {
            "description": "The email address of the author",
            "type": "string",
            "format": "email"
        },
        "url": {
            "description": "The URL to the homepage of the Tool",
            "type": "string",
            "format": "url"
        }
    },
    "required": [
        "name",
        "version",
        "license",
        "repository",
        "description",
        "author",
        "authorEmail",
        "url"
    ]
}

=== Sage-Bionetworks/nlp-sandbox-schemas/test/json-samples/tool.json
{
    "name": "awesome-date-annotator",
    "version": "1.0.0",
    "license": "Apache-2.0",
    "repository": "github:awesome-org/awesome-date-annotator",
    "description": "An awesome Date Annotator based on regex patterns",
    "author": "The author of the Tool",
    "authorEmail": "author@example.com",
    "url": "https://example.com"
}
